# Пользователи
## Регистрация пользователя

POST http://localhost:4200/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "me@overlook.net",
  "avatar": "torrance.png",
  "firstname": "Jack",
  "lastname": "Torrance",
  "password": "shining"
}

###

## Авторизация пользователя

POST http://localhost:4200/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "me@overlook.net",
  "password": "shining"
}

###

## Выход пользователя

POST http://localhost:4200/users/logout HTTP/1.1
Content-Type: application/json

{
  "email": "me@overlook.net"
}

###

# Фильмы

## Создание

POST http://localhost:4200/films/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyIkX18iOnsiYWN0aXZlUGF0aHMiOnsicGF0aHMiOnsicGFzc3dvcmQiOiJpbml0IiwiZW1haWwiOiJpbml0IiwibmFtZSI6ImluaXQiLCJfaWQiOiJpbml0IiwiYXZhdGFyIjoiaW5pdCIsImNyZWF0ZWRBdCI6ImluaXQiLCJ1cGRhdGVkQXQiOiJpbml0IiwiX192IjoiaW5pdCJ9LCJzdGF0ZXMiOnsicmVxdWlyZSI6e30sImluaXQiOnsiX2lkIjp0cnVlLCJuYW1lIjp0cnVlLCJlbWFpbCI6dHJ1ZSwiYXZhdGFyIjp0cnVlLCJwYXNzd29yZCI6dHJ1ZSwiY3JlYXRlZEF0Ijp0cnVlLCJ1cGRhdGVkQXQiOnRydWUsIl9fdiI6dHJ1ZX19fSwic2tpcElkIjp0cnVlfSwiJGlzTmV3IjpmYWxzZSwiX2RvYyI6eyJfaWQiOiI2M2I2YmQ5MDQ0NjQxNjExZTkyZDFkZTAiLCJuYW1lIjoiSmFjayBUb3JyYW5jZSIsImVtYWlsIjoibWVAb3Zlcmxvb2submV0IiwiYXZhdGFyIjoibDVFaElMclBxODQuanBnIiwicGFzc3dvcmQiOiI2MjU2ZTljNmM0MGVlOTA5NTM0YWY2NjI0YWZmNThkYTQ4ZjkwMDJjNWQ4YWIyOWFlOTI0ZDQ1OTkyMjVlZjc4IiwiY3JlYXRlZEF0IjoiMjAyMy0wMS0wNVQxMjowNzo0NC4xMjFaIiwidXBkYXRlZEF0IjoiMjAyMy0wMS0wNVQxMjowNzo0NC4xMjFaIiwiX192IjowfSwiaWF0IjoxNjcyOTIwNTc3LCJleHAiOjE2NzMwOTMzNzd9.eufjp3w9N1PIT0AYLtIwOulasukshjLIW7nZQvyQCnU

{
  "title": "Filmdsvsd",
  "description": "Film description Film description Film description Film description Film description Film description",
  "publicationDate": "2020",
  "genre": "comedy",
  "releaseYear": 2020,
  "rating": 9.7,
  "previewLink": "dsvnjkv",
  "link": "link",
  "actors": ["1", "2", "3"],
  "producer": "producer",
  "durationInMinutes": 130,
  "userId": "6374d4c33d8026ef445dac97",
  "posterLink": "mdkskmkv",
  "backgroundImageLink": "dnvkkdafv",
  "backgroundColor": "ndnjvnkja"
}

###

## Редактирование

POST http://localhost:4200/films/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyIkX18iOnsiYWN0aXZlUGF0aHMiOnsicGF0aHMiOnsicGFzc3dvcmQiOiJpbml0IiwiZW1haWwiOiJpbml0IiwibmFtZSI6ImluaXQiLCJfaWQiOiJpbml0IiwiYXZhdGFyIjoiaW5pdCIsImNyZWF0ZWRBdCI6ImluaXQiLCJ1cGRhdGVkQXQiOiJpbml0IiwiX192IjoiaW5pdCJ9LCJzdGF0ZXMiOnsicmVxdWlyZSI6e30sImluaXQiOnsiX2lkIjp0cnVlLCJuYW1lIjp0cnVlLCJlbWFpbCI6dHJ1ZSwiYXZhdGFyIjp0cnVlLCJwYXNzd29yZCI6dHJ1ZSwiY3JlYXRlZEF0Ijp0cnVlLCJ1cGRhdGVkQXQiOnRydWUsIl9fdiI6dHJ1ZX19fSwic2tpcElkIjp0cnVlfSwiJGlzTmV3IjpmYWxzZSwiX2RvYyI6eyJfaWQiOiI2M2I2YmQ5MDQ0NjQxNjExZTkyZDFkZTAiLCJuYW1lIjoiSmFjayBUb3JyYW5jZSIsImVtYWlsIjoibWVAb3Zlcmxvb2submV0IiwiYXZhdGFyIjoibDVFaElMclBxODQuanBnIiwicGFzc3dvcmQiOiI2MjU2ZTljNmM0MGVlOTA5NTM0YWY2NjI0YWZmNThkYTQ4ZjkwMDJjNWQ4YWIyOWFlOTI0ZDQ1OTkyMjVlZjc4IiwiY3JlYXRlZEF0IjoiMjAyMy0wMS0wNVQxMjowNzo0NC4xMjFaIiwidXBkYXRlZEF0IjoiMjAyMy0wMS0wNVQxMjowNzo0NC4xMjFaIiwiX192IjowfSwiaWF0IjoxNjcyOTIwNTc3LCJleHAiOjE2NzMwOTMzNzd9.eufjp3w9N1PIT0AYLtIwOulasukshjLIW7nZQvyQCnU

{
  "id": "1",
  "title": "Film updated",
  "description": "Film description Film description Film description Film description Film description Film description",
  "publicationDate": "2020",
  "genre": "comedy",
  "releaseYear": 2020,
  "rating": 9.7,
  "previewLink": "dsvnjkv",
  "link": "link",
  "actors": ["1", "2", "3"],
  "producer": "producer",
  "durationInMinutes": 130,
  "userId": "6374d4c33d8026ef445dac97",
  "posterLink": "mdkskmkv",
  "backgroundImageLink": "dnvkkdafv",
  "backgroundColor": "ndnjvnkja"
}

###


